<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKme5epx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKme5epx/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerKme5epx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerKme5epx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerKme5epx\appProdProjectContainer([
    'container.build_hash' => 'Kme5epx',
    'container.build_id' => '4470c246',
    'container.build_time' => 1582135865,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKme5epx');
